name: Tree

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README.md
        run: ./.tree.sh
      - name: Commit README.md
        run: |
          git config --global user.name 'Mingi Ryu'
          git config --global user.email 'mingi.ryu@icloud.com'
          git commit -am "Update README.md"
          git push
